# -*- coding: utf-8 -*-
"""Sweden_Project.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1aFZ51PSa1lnXEGKfmJZ_G-8gbKI4ouiN
"""



import pandas as pd

df = pd.read_csv('/content/Waste_Dataset_V1.csv')
display(df.head())

df['ArrivalDate'] = pd.to_datetime(df['ArrivalDate'], format='%d-%m-%Y', errors='coerce')
df['ExpiryDate'] = pd.to_datetime(df['ExpiryDate'], format='%d-%m-%Y', errors='coerce')

print("Data types after conversion:")
print(df[['ArrivalDate', 'ExpiryDate']].info())

display(df.head())

df['OnPromotion'] = df['OnPromotion'].map({'Yes': True, 'No': False})

print("Data types after conversion:")
print(df[['OnPromotion']].info())

display(df.head())

for col in ['Category', 'SuggestedAction', 'StoreLocation']:
    df[col] = df[col].astype('category')

print("Data types after conversion:")
print(df[['Category', 'SuggestedAction', 'StoreLocation']].info())

display(df.head())

# Fill missing 'Zone' values based on 'StoreLocation'
df.loc[(df['StoreLocation'].isin(['Bangalore', 'Chennai'])) & (df['Zone'].isna()), 'Zone'] = 'South'
df.loc[(df['StoreLocation'] == 'Kanpur') & (df['Zone'].isna()), 'Zone'] = 'North'

# Fill remaining missing 'Zone' values if any, with a generic placeholder or based on further logic if needed.
# For now, let's just make sure it's a category type after filling some values
df['Zone'] = df['Zone'].astype('category')

# Fill missing 'TemperatureSupport' values with 'Not Recorded'
df['TemperatureSupport'] = df['TemperatureSupport'].fillna('Not Recorded')

print("Data types and non-null counts after filling missing values:")
print(df[['Zone', 'TemperatureSupport']].info())

display(df.head())

date_difference = df['ExpiryDate'] - df['ArrivalDate']

# Check if any ExpiryDate is not greater than ArrivalDate
invalid_dates_count = date_difference[date_difference <= pd.Timedelta(seconds=0)].count()

if invalid_dates_count == 0:
    print("Verification successful: ExpiryDate is always greater than ArrivalDate.")
else:
    print(f"Verification failed: Found {invalid_dates_count} instances where ExpiryDate is not greater than ArrivalDate.")
    print("These instances are:")
    display(df[date_difference <= pd.Timedelta(seconds=0)])

df['DaysUntilExpiry'] = (df['ExpiryDate'] - df['ArrivalDate']).dt.days

print("Data types after recalculation:")
print(df[['ArrivalDate', 'ExpiryDate', 'DaysUntilExpiry']].info())

display(df.head())

median_days_until_expiry = df['DaysUntilExpiry'].median()
pct_90_days_until_expiry = df['DaysUntilExpiry'].quantile(0.90)

print(f"Median DaysUntilExpiry: {median_days_until_expiry}")
print(f"90th Percentile DaysUntilExpiry: {pct_90_days_until_expiry}")

outliers_df = df[df['DaysUntilExpiry'] > pct_90_days_until_expiry]

print(f"\nNumber of outliers (DaysUntilExpiry > 90th percentile): {len(outliers_df)}")
print("\nOutliers by Category (DaysUntilExpiry > 90th percentile):")
display(outliers_df.groupby('Category')['DaysUntilExpiry'].agg(['count', 'min', 'max', 'mean']))

print("\nSample of outlier data:")
display(outliers_df.head())

display(df.head())

df['ItemName'] = df['ItemName'].str.strip().str.capitalize()
df['Brand'] = df['Brand'].str.strip().str.capitalize()

print("Unique values for ItemName after cleaning (first 10):\n", df['ItemName'].unique()[:10])
print("\nUnique values for Brand after cleaning (first 10):\n", df['Brand'].unique()[:10])

df.to_csv('Waste_Dataset_Processed.csv', index=False)
print("DataFrame exported to 'Waste_Dataset_Processed.csv' successfully.")